### PR TITLE
Update tic.R templates

### PR DESCRIPTION
**Pull request by pat-s**
@maelle @yonicd	

I've put commented examples of your two project use cases in the `tic.R` pkg template. Can you take a look and tell whether this is fine for you?

`inst/templates/package/tic.R`

#### Other changes

* Disentangled the "before_install" stage. 
* Add link to _tic_ pkgdown site in header of `.travis.yml`

### CODE REVIEW

**Comment by yonicd** [comment]
Looks good by me. 

Only thing is that the repo is moving this week to a different GH owner, so it may be worthwhile to use the new GH address in the template links.

**Comment by yonicd** [comment]
looks ok for me.

**Comment by maelle** [comment]
Thanks. I wonder whether having all these comments makes the tic.R look scary?

**Comment by yonicd** [comment]
Imo it is missing some annoted examples, which is scarier.

**Comment by pat-s** [comment]
> Imo it is missing some annoted examples, which is scarier.

Can you give an example what you mean here?

**Comment by krlmlr** [comment]
Thanks. I cherry-picked and tweaked the changes to `.travis.yml` . Will tweak `tic.R`.

We could also create demo projects that show how to auto-build documentation and covrpage.

**Pull request closed without merging**
