### PR TITLE
usethis project compliance

### PR DESCRIPTION
**Pull request by maelle**
cf #89

### CODE REVIEW

**Comment by krlmlr** [comment]
Deploy preview for *eloquent-wescoff-5685d5* ready!

Built with commit d38494606dc0b05a731f8f5c73cbfe0580ead856

https://deploy-preview-96--eloquent-wescoff-5685d5.netlify.com

**Comment by maelle** [comment]
My very professional edits consisted in looking for all occurrences of `"."` :see_no_evil:

**Comment by krlmlr** [comment]
Thanks! I think we could even get rid of the `path` argument?

**Comment by maelle** [comment]
Why?

**Comment by krlmlr** [comment]
Because one can always do

```r
usethis::with_project(path = "...", ...)
```

. I removed the `path` argument to `tic::use_tic()` already.

**Comment by maelle** [comment]
aaah ok!

**Pull request merged**
