### PR TITLE
Move get_public_key and encode_private_key to tic

### PR DESCRIPTION
**Pull request by pat-s**
and import `openssl` functions. Is this desired or do your prefer keeping the `openssl::` syntax?

https://github.com/ropenscilabs/tic/issues/67

Can only be merged after https://github.com/ropenscilabs/tic/pull/71

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks. I don't think we need to import _tic_ here if the setup functionality moves to _usethis_. We can duplicate these functions in _tic_ for now to disentangle.

I prefer the `::` notation if only few functions are used from a package.

**Comment by pat-s** [comment]
> We can duplicate these functions in tic for now to disentangle.

Ok, so just copy and not move?

> I prefer the :: notation if only few functions are used from a package.

So go back to the `::` notation?

**Comment by krlmlr** [comment]
Yes, but I can take care of that. Let's keep `::` .

**Comment by pat-s** [comment]
Stale.

**Pull request closed without merging**
